<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

require APPPATH . '/libraries/BaseControllerWeb.php';

class  Tbl_restaurantbooking_table extends BaseControllerWeb
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_restaurantbooking_table_model');
		$this->load->helper('url');
		$this->load->library('language', array('controller' => $this->router->class));
    } 

    /*
     * Listing of tbl_restaurantbooking_tables
     */
    function index()
    {
        $data['tbl_restaurantbooking_tables'] = $this->Tbl_restaurantbooking_table_model->get_all_tbl_restaurantbooking_tables();
//        $data['_view'] = 'tbl_restaurantbooking_table/index';
        // $this->load->view('tbl_restaurantbooking_table/index',$data);
		$this->global['pageTitle'] = 'TIQS : IMAGELOCATION';
		$this->loadViews('tbl_restaurantbooking_table/index', $this->global, $data, NULL, "headerpublic"); // payment screen
	}

    /*
     * Adding a new tbl_restaurantbooking_table
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'width' => $this->input->post('width'),
				'height' => $this->input->post('height'),
				'top' => $this->input->post('top'),
				'left' => $this->input->post('left'),
				'name' => $this->input->post('name'),
				'seats' => $this->input->post('seats'),
				'minimum' => $this->input->post('minimum'),
				'imageid' => $this->input->post('imageid'),
            );
            
            $tbl_restaurantbooking_table_id = $this->Tbl_restaurantbooking_table_model->add_tbl_restaurantbooking_table($params);
            redirect('tbl_restaurantbooking_table/index');
        }
        else
        {            
//            $data['_view'] = 'tbl_restaurantbooking_table/add';
//            $this->load->view('tbl_restaurantbooking_table/add',$data);
			$this->global['pageTitle'] = 'TIQS : IMAGELOCATION';
			$this->loadViews('tbl_restaurantbooking_table/add', $this->global, NULL, NULL, "headerpublic"); // payment screen

		}
    }  

    /*
     * Editing a tbl_restaurantbooking_table
     */
    function edit($id)
    {   
        // check if the tbl_restaurantbooking_table exists before trying to edit it
        $data['tbl_restaurantbooking_table'] = $this->Tbl_restaurantbooking_table_model->get_tbl_restaurantbooking_table($id);
        
        if(isset($data['tbl_restaurantbooking_table']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'width' => $this->input->post('width'),
					'height' => $this->input->post('height'),
					'top' => $this->input->post('top'),
					'left' => $this->input->post('left'),
					'name' => $this->input->post('name'),
					'seats' => $this->input->post('seats'),
					'minimum' => $this->input->post('minimum'),
					'userid' => $this->input->post('userid'),
					'floorplanimage' => $this->input->post('floorplanimage'),
                );

                $this->Tbl_restaurantbooking_table_model->update_tbl_restaurantbooking_table($id,$params);            
                redirect('tbl_restaurantbooking_table/index');
            }
            else
            {
                $data['_view'] = 'tbl_restaurantbooking_table/edit';
                $this->load->view('tbl_restaurantbooking_table/edit',$data);
            }
        }
        else
            show_error('The tbl_restaurantbooking_table you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_restaurantbooking_table
     */
    function remove($id)
    {
        $tbl_restaurantbooking_table = $this->Tbl_restaurantbooking_table_model->get_tbl_restaurantbooking_table($id);

        // check if the tbl_restaurantbooking_table exists before trying to delete it
        if(isset($tbl_restaurantbooking_table['id']))
        {
            $this->Tbl_restaurantbooking_table_model->delete_tbl_restaurantbooking_table($id);
            redirect('tbl_restaurantbooking_table/index');
        }
        else
            show_error('The tbl_restaurantbooking_table you are trying to delete does not exist.');
    }
    
}
